tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up


ports:
  - port: 18000
    onOpen: ignore

vscode:
  extensions:
    - golang.go
    - ms-azuretools.vscode-docker
